version: '3.7'
services:
  sidekick:
    image: minio/sidekick:v1.2.0
    tty: true
    ports:
    - "81:80"
    command: --health-path=/minio/health/ready --address :80 http://minio1:9000
  gateway:
    image:  minio/minio:RELEASE.2022-03-26T06-49-28Z
    command: gateway s3 http://sidekick --console-address ":19000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
    - "9000:9000"
    - "19000:19000"
  openresty:
    image: openresty/openresty:1.21.4.1-alpine-fat
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx.log:/var/log/nginx.log
    ports:
      - "80:80"
  minio1:
    image: minio/minio:RELEASE.2022-03-26T06-49-28Z
    volumes:
      - data1-1:/data1
    ports:
      - "9001:9000"
      - "19001:19001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DOMAIN: dalongrong.com
      MINIO_HTTP_TRACE: /var/log/minio.log
    command: server /data1 --console-address ":19001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  data1-1:
